GET http://localhost:8080/contacts

###

GET http://localhost:8080/contacts/67ce24b8aa44d8ad8545ead5

###

POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "jdoe@example.com",
  "favoriteColor": "blue",
  "birthDate": "01/01/1990"
}

###

PUT http://localhost:8080/contacts/67ce24b8aa44d8ad8545ead5
Content-Type: application/json

{
    "firstName": "Johnny"
}

###

DELETE http://localhost:8080/contacts/67d7b4bcf820821f35d75308

###

GET https://cse341-contacts-5u7a.onrender.com/contacts

###

GET https://cse341-contacts-5u7a.onrender.com/contacts/67ce24b8aa44d8ad8545ead5

###

POST https://cse341-contacts-5u7a.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "jdoe@example.com",
  "favoriteColor": "blue",
  "birthDate": "01/01/1990"
}

###

PUT https://cse341-contacts-5u7a.onrender.com/contacts/67ce24b8aa44d8ad8545ead5
Content-Type: application/json

{
    "firstName": "Johnny"
}

###

DELETE https://cse341-contacts-5u7a.onrender.com/contacts/67d8f17153ee20eda433c6e1